In [ ]:
# !pip install numpy

In [ ]:
#!pip install pandas matplotlib seaborn scikit-learn

27-34

In [22]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, precision_score , recall_score , accuracy_score, f1_score


In [5]:
# Load Iris dataset
iris = datasets.load_iris()

# Create DataFrame for better visualization
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df.to_csv('iris_dataset.csv', index=False)
df['target'] = iris.target
df['target_name'] = df['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

print(df.head())
print("\nData Information:")
print(df.info())
print("\nMissing Values:")
print(df.isnull().sum())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_name  
0       0      setosa  
1       0      setosa  
2       0      setosa  
3       0      setosa  
4       0      setosa  

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (

In [ ]:
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


Linear KERNEL

In [8]:
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)


SVC(kernel='linear', random_state=42)

In [9]:
y_pred = svm_model.predict(X_test)

In [10]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[15  0  0]
 [ 0 14  1]
 [ 0  3 12]]


In [11]:
precision = precision_score(y_test, y_pred, average=None)
print("\nPrecision (per class):", precision)

# For overall precision
precision_macro = precision_score(y_test, y_pred, average='macro')
print("Average Precision (Macro):", precision_macro)

# Detailed report
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=iris.target_names))



Precision (per class): [1.         0.82352941 0.92307692]
Average Precision (Macro): 0.9155354449472096

Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       0.82      0.93      0.88        15
   virginica       0.92      0.80      0.86        15

    accuracy                           0.91        45
   macro avg       0.92      0.91      0.91        45
weighted avg       0.92      0.91      0.91        45



In [23]:
precision = precision_score(y_test, y_pred, average=None)
print("\nPrecision (per class):", precision)
recall = recall_score(y_test, y_pred, average=None)
print("\nRecall (per class):", recall)

# For overall precision and recall
print("Average Precision (Macro):", precision_score(y_test, y_pred, average='macro'))
print("Average Recall (Macro):", recall_score(y_test, y_pred, average='macro'))

accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

f1_measure = f1_score(y_test, y_pred, average=None)
print("\nF1-Measure (per class):", f1_measure)

print("Average F1-Measure (Macro):", f1_score(y_test, y_pred, average='macro'))

# Detailed report
# print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=iris.target_names))



Precision (per class): [1.         0.82352941 0.92307692]

Recall (per class): [1.         0.93333333 0.8       ]
Average Precision (Macro): 0.9155354449472096
Average Recall (Macro): 0.9111111111111111

Accuracy: 0.9111111111111111

F1-Measure (per class): [1.         0.875      0.85714286]
Average F1-Measure (Macro): 0.9107142857142857


RBF KERNEL

In [18]:
svm_rbf_model = SVC(kernel='rbf',C=1.0, gamma='scale', random_state=42)
svm_rbf_model.fit(X_train, y_train)

SVC(random_state=42)

In [19]:
y_pred_rbf=svm_rbf_model.predict(X_test)

In [20]:
cm_rbf=confusion_matrix(y_test, y_pred_rbf)
print("RBF Kernel Confusion Matrix:\n", cm_rbf)

RBF Kernel Confusion Matrix:
 [[15  0  0]
 [ 0 14  1]
 [ 0  2 13]]


In [24]:
precision_rbf = precision_score(y_test, y_pred, average=None)
print("\nPrecision (per class):", precision_rbf)

recall_rbf = recall_score(y_test, y_pred, average=None)
print("\nRecall (per class):", recall_rbf)

# For overall precision and recall
print("Average Precision (Macro):", precision_score(y_test, y_pred_rbf, average='macro'))
print("Average Recall (Macro):", recall_score(y_test, y_pred_rbf, average='macro'))

accuracy_rbf = accuracy_score(y_test, y_pred_rbf)
print("\nRBF Kernel Accuracy:", accuracy_rbf)

f1_measure_rbf = f1_score(y_test, y_pred_rbf, average=None)
print("\nRBF Kernel F1-Measure (per class):", f1_measure_rbf)

print("Average RBF Kernel F1-Measure (Macro):", f1_score(y_test, y_pred_rbf, average='macro'))


Precision (per class): [1.         0.82352941 0.92307692]

Recall (per class): [1.         0.93333333 0.8       ]
Average Precision (Macro): 0.9345238095238096
Average Recall (Macro): 0.9333333333333332

RBF Kernel Accuracy: 0.9333333333333333

RBF Kernel F1-Measure (per class): [1.         0.90322581 0.89655172]
Average RBF Kernel F1-Measure (Macro): 0.9332591768631814
